### ISSUE TITLE
New skeleton - Tapestry

### ISSUE THREAD

**Issue by MSaifAsif** [MSaifAsif/sample-skeleton-projects#18]
Need implementation of Apache Tapestry

**Comment by MSaifAsif** [comment]
Facing the following issue

```java
Caused by: java.lang.RuntimeException: Error building service proxy for service 'RegistryStartup' (at org.apache.tapestry5.ioc.internal.services.RegistryStartup(Logger, List) (at RegistryStartup.java:36) via org.apache.tapestry5.ioc.services.TapestryIOCModule.bind(ServiceBinder) (at TapestryIOCModule.java:49)): java.lang.IllegalArgumentException
	at org.apache.tapestry5.ioc.internal.ModuleImpl$4.invoke(ModuleImpl.java:327)
	at org.apache.tapestry5.ioc.internal.OperationTrackerImpl.invoke(OperationTrackerImpl.java:74)
	... 57 more
Caused by: java.lang.IllegalArgumentException
	at org.apache.tapestry5.internal.plastic.asm.ClassReader.<init>(ClassReader.java:167)
	at org.apache.tapestry5.internal.plastic.asm.ClassReader.<init>(ClassReader.java:153)
	at org.apache.tapestry5.internal.plastic.PlasticInternalUtils.convertBytecodeToClassNode(PlasticInternalUtils.java:436)
	at org.apache.tapestry5.internal.plastic.PlasticClassPool.constructClassNodeFromBytecode(PlasticClassPool.java:481)
	at org.apache.tapestry5.internal.plastic.PlasticClassPool$1.convert(PlasticClassPool.java:62)
	at org.apache.tapestry5.internal.plastic.PlasticClassPool$1.convert(PlasticClassPool.java:59)
	at org.apache.tapestry5.internal.plastic.Cache.get(Cache.java:37)
	at org.apache.tapestry5.internal.plastic.PlasticClassPool.getTypeCategory(PlasticClassPool.java:562)
	at org.apache.tapestry5.internal.plastic.PlasticMethodImpl.invokeDelegateAndReturnResult(PlasticMethodImpl.java:363)
	at org.apache.tapestry5.internal.plastic.PlasticMethodImpl.access$000(PlasticMethodImpl.java:24)
	at org.apache.tapestry5.internal.plastic.PlasticMethodImpl$2.doBuild(PlasticMethodImpl.java:221)
	at org.apache.tapestry5.internal.plastic.InstructionBuilderImpl.doCallback(InstructionBuilderImpl.java:832)
	at org.apache.tapestry5.internal.plastic.PlasticMethodImpl.changeImplementation(PlasticMethodImpl.java:130)
	at org.apache.tapestry5.internal.plastic.PlasticMethodImpl.delegateTo(PlasticMethodImpl.java:203)

```
